[package]
name = "rustcraft"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-executor = "0.3.27"
serde = "1.0.158"
serde_derive = "1.0.158"
serde_json = "1.0.94"
wgpu = "0.15.1"
winit = "0.28.3"
zip = "0.6.4"


